### ISSUE TITLE
CsvRegexReplaceを使用した部分一致の置換が行えない

### ISSUE THREAD

**Issue by shikazuki** [mygreen/super-csv-annotation#34]
## 概要
CsvRegexReplaceのアノテーションを使用して正規表現に該当する任意の文字列を複数置換することができません。

## 修正案
https://github.com/mygreen/super-csv-annotation/blob/026ddd555993129231be94485533777ce52a1841/src/main/java/com/github/mygreen/supercsv/cellprocessor/conversion/RegexReplace.java#L77-L83

`matcher.matches()`を使用すると完全一致の比較になってしまいます。
部分一致させて`matcher.replacheAll()`を呼ぶ場合、`matcher.find()`が適切かと思います。

または、CsvRegexReplaceはCsvRegexReplaceFirstとして、CsvRegexReplaceAllとして作成したほうが良いでしょうか？

**Comment by mygreen** [comment]
2種類用意するならば、アノテーションの属性で設定を切り替えられるようにした方がいい気がします。

- ``@CsvRegexpReplace(method=MatchMethod.All)`` - 今までの全体一致
- ``@CsvRegexpReplace(method=MatchMethod.Partial)`` - 部分一致
